<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
	<PackageReference Include="Avalonia.AvaloniaEdit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameEngine.Core\GameEngine.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\TextureEditor.axaml.cs">
      <DependentUpon>TextureEditor.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ProjectEditor.axaml.cs">
      <DependentUpon>ProjectEditor.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\AnimationEditor.axaml.cs">
      <DependentUpon>AnimationEditor.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\LevelEditor.axaml.cs">
      <DependentUpon>LevelEditor.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AssetEditorWindow.axaml.cs">
      <DependentUpon>AssetEditorWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>