<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <UserSecretsId>5d9292ac-f3f7-4ac4-868d-040fd4f514d6</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
	<RunAOTCompilation>true</RunAOTCompilation>
	<WasmStripILAfterAOT>true</WasmStripILAfterAOT>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameEngine.Runner.Avalonia\GameEngine.Runner.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="../../GameEngine.Demo/assets/**/*.*" Link="Assets/game/%(RecursiveDir)$([System.String]::Copy('%(FileName)').Replace('.','_'))%(Extension)" />
	<AvaloniaResource Include="../../GameEngine.Demo/levels/**/*.*" Link="Assets/game/levels/%(RecursiveDir)$([System.String]::Copy('%(FileName)').Replace('.','_'))%(Extension)" />
    <AvaloniaResource Include="../../GameEngine.Demo/assets.txt" Link="Assets/assets.txt" />
  </ItemGroup>
</Project>