<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GameTemplate.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="GameEngine.Runner.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameTemplate\GameTemplate.csproj" />
  </ItemGroup>
</Project>
