<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameEngine.Runner.Avalonia\GameEngine.Runner.Avalonia.csproj" />
    <ProjectReference Include="..\..\GameEngine.Demo\GameEngine.Demo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="../../GameEngine.Demo/assets.txt" Link="assets.txt" />
    <BundleResource Include="../../GameEngine.Demo/assets/**/*.*" Link="assets/%(RecursiveDir)%(FileName)%(Extension)" />
    <BundleResource Include="../../GameEngine.Demo/levels/**/*.*" Link="levels/%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>
</Project>